#!/usr/bin/env node
/**
 * Every `aliases` entry in the corpus, as redirect pairs.
 *
 * Reads the markdown directly rather than going through Astro: the schema is
 * plain Zod for exactly this reason (see the header of `src/schema/frontmatter.ts`),
 * and a redirect map that could only be generated by booting the site generator
 * would be unusable from CI checks and from the agent's tooling.
 *
 * Drafts are collected too, and that is safe: their target is not in a
 * production build, so `againstBuild()` holds the redirect back until the
 * article is published.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';

import type { Redirect } from '../src/redirects.ts';
import { frontmatter } from '../src/schema/frontmatter.ts';

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---/;

export function collectAliases(postsDir: string): Redirect[] {
  const out: Redirect[] = [];
  for (const name of readdirSync(postsDir)) {
    if (!name.endsWith('.md')) continue;
    const block = FRONTMATTER.exec(readFileSync(join(postsDir, name), 'utf8'));
    if (!block) throw new Error(`${name}: no frontmatter block`);
    const parsed = frontmatter.safeParse(parseYaml(block[1]));
    if (!parsed.success) throw new Error(`${name}: ${parsed.error.message}`);
    const { slug, aliases } = parsed.data;
    for (const from of aliases ?? []) {
      out.push({ from, to: `/posts/${slug}/`, section: `aliases:${slug}` });
    }
  }
  return out;
}
